name: simple_coffee
description: "An app to order coffee from a coffee shop."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  social_media_flutter: ^0.0.2
  shared_preferences: ^2.0.15
  flutter_swipe_button: ^2.1.1+1
  swipeable_button_view: ^0.0.2
  lottie: ^2.4.0
  page_transition: ^2.0.9
  url_launcher: ^6.0.20
  provider: ^6.1.1
  wave: 0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app/
    - assets/app/OnBoarding/
    - assets/app/OnBoarding/SignIn/
    - assets/app/products_assets/
    - assets/app/products_assets/cappuccinos/
    - assets/app/products_assets/machiatos/
    - assets/app/products_assets/lattes/

linter:
  rules:
    avoid_print: false